### ISSUE TITLE
Move Designer issues to mdw-designer repository

### ISSUE THREAD

**Issue by donaldoakes** [CenturyLinkCloud/mdw#111]
https://github.com/CenturyLinkCloud/mdw-designer

Then remove the designer label, project and milestones from this repo.

Closed issues do not need to be moved.

**Comment by ab59451** [comment]
Using the chrome plugin "Kamino" to migrate the issues from one repo to other .

**Comment by ab59451** [comment]
chrome plugin didn't work. Moved the defects manually.

**Comment by ab59451** [comment]
migrated this issue to the mdw-designer repo.
closed the issue,removed the milestone, removed the designer label , removed the project and marked as duplicate in this repo.
