### ISSUE TITLE
Enhance DB transactions to retry in case of deadlock/lock timeouts automatically

### ISSUE THREAD

**Issue by donaldoakes** [CenturyLinkCloud/mdw#116]
We need this to resolve MySQL deadlock scenarios through [Spring Retry](https://github.com/spring-projects/spring-retry).  Here's a good article on this subject:
https://spring.io/blog/2011/08/15/configuring-spring-and-jta-without-full-java-ee/

**Comment by donaldoakes** [comment]
It seems like the best open-source JTA impls are these:
 - http://narayana.io/
 - https://www.atomikos.com/Main/TransactionsEssentials

Narayana sounds promising to me.

**Comment by jbrojdeCTL** [comment]
Will implement our own retry mechanism instead of spring-retry

**Comment by jbrojdeCTL** [comment]
Due to complications with nesting of some transactions, we decided to apply the retry functionality only to in the case of deadlock, and not to ALL transactions.   This does resolve the issue of deadlocks with event waits however.
