### ISSUE TITLE
Docker image for mdw6

### ISSUE THREAD

**Issue by donaldoakes** [CenturyLinkCloud/mdw#12]
Tomcat, MySQL (or embedded db), mdw.war and configs.

**Comment by donaldoakes** [comment]
Remaining work:
 - Find a workable solution for embedded db (based on --user).
 - Complete documentation in the [Docker Guide](http://centurylinkcloud.github.io/mdw/docs/guides/docker-guide/).
 - Automated builds on Docker Hub: https://docs.docker.com/docker-hub/builds/.

**Comment by jbrojdeCTL** [comment]
Still need to set up automated builds

**Comment by magrawa** [comment]
Let me know if you want me to look into 
Automated builds on Docker Hub: https://docs.docker.com/docker-hub/builds/

**Comment by magrawa** [comment]
#380
