### ISSUE TITLE
Compare MongoDB and MySQL performance for inserting CLOB

### ISSUE THREAD

**Issue by magrawa** [CenturyLinkCloud/mdw#127]
Create a small Java program to insert into a table similar to Document table and compare the performance between MongoDB and MySQL DB. 
You can have 10 KB document size 
Measure the time taken to insert at following table size.
5000
50,000
100,000

**Comment by donaldoakes** [comment]
I suggest you may also want to select by contents document_id and compare that performance as well.

**Comment by jbrojdeCTL** [comment]
I think the test should involve testing insert/update (by ID)/select (by ID) from a table with same definition as DOCUMENT_CONTENT (MySQL) versus same operations a collection (i.e. table) in MongoDB.

**Comment by ab59451** [comment]
HI ,

I have attached the sample codes used . this can be run on any machine to measure the performance. Number of rows and size of the "content" column and the content of the "CONTENT " column can be modified in the code as per the requirement. 

NOTE: the db properties to be included in the code as per the environment.The file is uploaded as .txt format. change the file type to .java before using. 


[MongoDBInsert.txt](https://github.com/CenturyLinkCloud/mdw/files/1144234/MongoDBInsert.txt)
[MySqlInsert.txt](https://github.com/CenturyLinkCloud/mdw/files/1144235/MySqlInsert.txt)

**Comment by magrawa** [comment]
Looks good. Can you please plot a graph with 5,10,50, 100 K rows size on x axis and Mongo DB and MySQL time to do a insert, update and select on Y axis. You can use spread sheets to do that.
Thanks,
Manoj
