### ISSUE TITLE
Intra-MDW dependencies incorrectly reflected in published .pom artifacts

### ISSUE THREAD

**Issue by donaldoakes** [CenturyLinkCloud/mdw#132]
Here's an example from mdw-workflow:
http://repo1.maven.org/maven2/com/centurylink/mdw/mdw-workflow/6.0.04/mdw-workflow-6.0.04.pom

The groupId for mdw dependencies is incorrectly created as mdw instead of com.centurylink.mdw:
```xml
    <dependency>
      <groupId>mdw</groupId>
      <artifactId>mdw-common</artifactId>
      <version>6.0.04</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>mdw</groupId>
      <artifactId>mdw-services</artifactId>
      <version>6.0.04</version>
      <scope>compile</scope>
    </dependency>
```

**Comment by magrawa** [comment]
Hi Don,
It is due to the dependency we have in mdw-workflow
dependencies {
    compile project(":mdw-common")
    compile project(":mdw-services")
}

I tried this but then realised it will not change the project dependencies in pom.
uploadArchives {
    repositories {
      mavenDeployer {
        pom.project {
          groupId 'com.centurylink.mdw'}
      }
    }
}

How do I change that? Any suggestions?


Thanks,
Manoj

**Comment by donaldoakes** [comment]
This is fixed on branch issue_145 and will be delivered with its pull request.  Commit is 316868e.
