### ISSUE TITLE
Asset discovery service auto-includes asset subpackages

### ISSUE THREAD

**Issue by donaldoakes** [CenturyLinkCloud/mdw#138]
This is illustrated in the behavior of the [MDW CLI](http://centurylinkcloud.github.io/mdw/docs/guides/cli/).

When following the Quick Start Guide:
http://centurylinkcloud.github.io/mdw/docs/guides/quick-start/

The `mdw init` command downloads packages specified by [Setup](https://github.com/CenturyLinkCloud/mdw/blob/master/mdw-common/src/com/centurylink/mdw/cli/Setup.java).defaultBasePackages.  This includes "com.centurylink.mdw.testing", but not "com.centurylink.mdw.testing.postman", yet the postman package gets downloaded.

I suggest that we add a query param like `?recursive=true` to control inclusion of subpackages.

**Comment by jbrojdeCTL** [comment]
I need to resolve this issue in order to resolve issue #167
