### ISSUE TITLE
Runtime UI can overlook subprocess instances for superseded definitions

### ISSUE THREAD

**Issue by donaldoakes** [CenturyLinkCloud/mdw#161]
In the MDWHub instance view for Multiple Subprocess activities, subflow instances from non-current definition versions are not displayed in the Subprocesses Inspector tab.

Say subproc mypkg/MyProc was launched from version 1.2, and then subsequently v 1.3 was imported.

The REST resource URL looks like this:
mdw/services/Processes?definition=mypkg/MyProc v[1.1-2)&owner=PROCESS_INSTANCE&ownerId=123

Apparently this retrieves subproc instances that correspond to the latest version only (1.3 in this example).

**Comment by magrawa** [comment]
Issue is in this code         WorkflowServicesImpl.getProcesses()       
Process procDef = ProcessCache.getProcessSmart(spec);
Here we always get the latest version. 
Should we use SECONDRY_OWNER_ID to get all the instances of that activity?
Something like this :
select count(process_instance_id) from process_instance pi
where 1 = 1  and pi.owner = 'PROCESS_INSTANCE' and pi.owner_id = 11420 and SECONDRY_OWNER_ID= 53503

**Comment by donaldoakes** [comment]
Fixed.
