### ISSUE TITLE
MySQL cleanup script implementation

### ISSUE THREAD

**Issue by donaldoakes** [CenturyLinkCloud/mdw#168]
Cleanup-Runtime.sql uses PL/SQL routines and is coupled to Oracle.  We need a MySQL version of this.  Also these scripts should operate on END_DT instead of CREATE_DT so that , for example, if property ProcessExpirationAgeInDays=180 this cleans up flows that were **completed** 180 days ago instead of completed flows that **started** 180 days ago.

**Comment by magrawa** [comment]
Current  com.centurylink.mdw.timer.cleanup.ProcessCleanup. Please update this class also to work with MySQL.

**Comment by magrawa** [comment]
Biswa, This is a high priority item. I have assigned the Chart issue to Jeen so that you can focus on this.

**Comment by magrawa** [comment]
Should we change the approach of loading Cleanup-Runtime.sql. We can have this in db asset package and also ProcessCleanup in the same package as @RegisteredService(ScheduledJob.class). Teams who want cleanup functionality can configure it in manifest.yml . 

    "mdw.timer.task.ProcessCleanup.TimerClass": "com.centurylink.mdw.timer.cleanup.ProcessCleanup",
    "mdw.timer.task.ProcessCleanup.Schedule": "30 9 * * * *",
    "MDWFramework.ProcessCleanup-RuntimeCleanupScript": "Cleanup-Runtime.sql",
    "MDWFramework.ProcessCleanup-ProcessExpirationAgeInDays": "30",
    "MDWFramework.ProcessCleanup-ExternalEventExpirationAgeInDays": "30",
    "MDWFramework.ProcessCleanup-MaximumProcessExpiration": "50000",
