### ISSUE TITLE
Upgrade to version 2.x from 1.4 for commons-dbcp and commons-pool 

### ISSUE THREAD

**Issue by jbrojdeCTL** [CenturyLinkCloud/mdw#172]
MDW has long been using Apache DBCP 1.4 (meant Java 6) for its pools (Database, Marshallers/Unmarshallers, ActiveMQ). Upgrade to make use of Apache DBCP2 library targeted for Java 7+ instead. This will involve upgrading ActiveMQ also from our currently used 5.10.0 version.

**Comment by jbrojdeCTL** [comment]
MDW has long been using Apache DBCP 1.4 (meant Java 6) for its pools (Database, Marshallers/Unmarshallers, ActiveMQ).   Upgrade to make use of Apache DBCP2 library targeted for Java 7+ instead.   This will inbolve upgrading ActiveMQ also from our currently used 5.10.0 version.

**Comment by magrawa** [comment]
This contains some disruptive changes, such as build.gradle changes, and also changes in application-context.xml which will also require other teams declaring their own beans to make changes to their spring files.
