### ISSUE TITLE
Millisecond precision for db TIMESTAMP and DATETIME fields

### ISSUE THREAD

**Issue by donaldoakes** [CenturyLinkCloud/mdw#178]
For example: process_instance.create_dt, start_dt, and end_dt.

This may not require any code changes, at least for MySQL.  In any case, we need to stay compatible with the old non-precise db since the revised SQL scripts will only take effect going forward.

**Comment by jbrojdeCTL** [comment]
To be able to capture macroseconds (and milliseconds), the DB schema must match the new create_tables.sql scripts, plus also have this property set in mdw.properties:
mdw.database.macrosecondprecision.enable=true
