### ISSUE TITLE
Allow a mechanism to exclude certain test cases from full test run

### ISSUE THREAD

**Issue by magrawa** [CenturyLinkCloud/mdw#183]
When running test cases on AppFog  as part of the push in GitHub some test cases like **ldap** one fails. We need to develop a mechnism to exclude those types of test cases. 
Here are some of the ways to do it.
1. Read a file containing excluded  test cases: Put the file in config dir. You should be able to exclude whole package, Or use regular expressions. 
   cons: System test would need to push the changes in Git and then pull it back on the server
2. Or send the list of test Cases which needs to be run. This way you exclude the test cases from the list you do not want to run.
  pros: no need to update Git or server side.

**Comment by donaldoakes** [comment]
In the CLI, `mdw test` now supports the `--exclude` option which uses standard file globbing wildcards.
