### ISSUE TITLE
Add ability to create a Task Template from mdw-admin

### ISSUE THREAD

**Issue by PabitraKumar-Behera** [CenturyLinkCloud/mdw#19]
There are some problems with the current implementation. Currently a user cannot link directly to a specific template.
When saving, the change should be pushed to Git. However, there is always the possibility of changing. Therefore, when a user chooses to edit, the server repo should be checked against origin. Or should saving be performed on the users's hard-drive and uploaded?

**Comment by donaldoakes** [comment]
Covered by issue #9.
