### ISSUE TITLE
Publish mdw-buildpack to CenturyLink internal GitLab repo

### ISSUE THREAD

**Issue by donaldoakes** [CenturyLinkCloud/mdw#198]
Besides GitHub, we need to host the latest buildpack on CenturyLink's GitLab for internal deployments:
https://ne1itcprhas62.ne1.savvis.net/PCF_Buildpacks_PUB_DEV/mdw-buildpack

Apparently this is a matter of corporate policy to not depend on external repos for cf push.

Also, I think we should move build.md to an internal place since it contains CenturyLink-specific information.  Once we do that, we can add shared credentials that would otherwise be inappropriate.

**Comment by magrawa** [comment]
I have requested access, I do not know if I would get the owner access. It would be nice if we can get mdwapp user added as owner so we can use that from our Jenkins builds.

**Comment by magrawa** [comment]
created a Jenkins task to upload.
Did not move build.md yet
