### ISSUE TITLE
Camel support in mdw6

### ISSUE THREAD

**Issue by donaldoakes** [CenturyLinkCloud/mdw#2]
Migrate the mdw-camel bundle from MDW 5.5.  Instead of wiring in all the Camel dependencies (direct and transitive), let's implement this in the mdw6 version of the OOB package com.centurylink.mdw.camel. This package will include all the needed jars so that they don't have to be packed in to mdw.war.

**Comment by morgansheets** [comment]
We will also need to create a new Camel Cookbook (.md file) as well when the Camel support in mdw6 is available.
