### ISSUE TITLE
Populate asset archive from Git instead of during import

### ISSUE THREAD

**Issue by donaldoakes** [CenturyLinkCloud/mdw#207]
In the db we can maintain a mapping for each asset to associate its definition id with the corresponding Git commit.  Then as-needed we can populate the Archive directory for in-flights by checking out the appropriate asset version.  Since all Git history is available locally, this would not require fetching from remote.

Preliminary thought on the database table design:
```sql
CREATE TABLE ASSET_REF
(
  DEFINITION_ID    BIGINT       NOT NULL,
  DEFINITION_TYPE  VARCHAR(32)  NOT NULL,
  REF              VARCHAR(64)  NOT NULL  -- Git commit hash
)
```

**Comment by magrawa** [comment]
Do we have to export and import data from this table from test into prod? Or should we keep this map in Git itself, may be as part of package or version file?

**Comment by donaldoakes** [comment]
I think this table would be environment-specific and populated during import instead of (or along-with) the Archive updates.

**Comment by jbrojdeCTL** [comment]
A new DB table called ASSET_REF and its indexes need to be created for any MDW instance beginning with MDW 6.0.07 build
