### ISSUE TITLE
Need to upgrade Linux and OSX JARs for our embedded MariaDB to support issue #178

### ISSUE THREAD

**Issue by jbrojdeCTL** [CenturyLinkCloud/mdw#211]
The current JARs for MAriaDB for Linux and OSX in our db package are using versions of MariaDB that predate support for millisecond and microsecond precision in DATETIME/TIMESTAMP fields, which was added in MariaDB 10.0.    Our current JAR for Windows is using MariaDB 10.0 so it does allow to capture that level of precision.

**Comment by oakesville** [comment]
Now that we're on GitHub, I think we should fork from MariaDB4J master:
https://github.com/vorburger/MariaDB4j
This appears to have 10.x versions for all platforms.

We'll have to retrofit our customizations, but the fork will enable us to better track these.

**Comment by donaldoakes** [comment]
Fixed
