### ISSUE TITLE
Discover assets from Maven repositories

### ISSUE THREAD

**Issue by donaldoakes** [CenturyLinkCloud/mdw#215]
Currently in both MDWHub and Designer, mdw6 assets can be discovered from MDW server instances such as AppFog.  It would be preferable to publish assets to an established repository structure like Maven.  In MDW 5 we used to discover from Maven, but for mdw6 we'll make the following changes:
 - Instead of our home-brew JSON asset package format, we'll publish zip files (one per package).
 - In contrast to MDW 5 style maven assets, our published assets will follow standard Maven conventions for artifact/directory naming.
 - Instead of crawling HTML asset lists, we'll use the maven-central REST API for discovery:
   http://search.maven.org/ajaxsolr/images/MavenCentralAPIGuide.pdf

This enhancement supersedes Issue #180.

**Comment by naveena-bellamkonda** [comment]
Should we support both AppFog and MavenCentral discovery?
