### ISSUE TITLE
Javadocs are not produced correctly by the MDW build

### ISSUE THREAD

**Issue by donaldoakes** [CenturyLinkCloud/mdw#216]
The javadocs on our site are terribly out-of-date:
http://centurylinkcloud.github.io/mdw/docs/javadoc/
We should include in our build procedure a step to update these each time we publish a formal build.

Also, the mdw-javadoc jar on maven-central only includes docs for mdw-hub:
http://repo1.maven.org/maven2/com/centurylink/mdw/mdw/6.0.06/mdw-6.0.06-javadoc.jar

**Comment by magrawa** [comment]
We do have javadocs for other jar files 
http://repo1.maven.org/maven2/com/centurylink/mdw/mdw-common/6.0.06/
Do we want to remove javadocs from individual folders and put everything under mdw. I do not know if maven will allow that. Or do we want to duplicate in two places one at mdw and other in their respective folders like mdw-common in above example.

**Comment by donaldoakes** [comment]
Right.  Maven central requires javadoc jars for all published modules.  I think mdw-javadoc.jar should contain everything, like it did in mdw5.

But most importantly, during the build we should generate combined javadoc output into mdw/docs/_docs/javadoc so that things like allclasses-frame.html are comprehensive.  Then we can commit the updated javadoc folder so that changes will be reflected on our docs site.

**Comment by magrawa** [comment]
There is a Jenkins issue to commit from detached HEAD. 
https://issues.jenkins-ci.org/browse/JENKINS-6856
I had to create a separate Jenkins project (mdw6-javadoc) to upload generated javadoc. It is executed when we publish to maven

 
Notes:

[MDW6-Build] $ /bin/sh -xe /prod/ecom2/local/apps/tomcat/tomcat7-jenkins/temp/jenkins897246769530715501.sh
+ /prod/ecom2/local/apps/jgit/jgit/org.eclipse.jgit.pgm/target/git add docs/_docs/javadoc
+ /prod/ecom2/local/apps/jgit/jgit/org.eclipse.jgit.pgm/target/git commit -a -m 'Updated javadocs'
[detached HEAD 1551ac6fbeb2e2bd5653f856dd2906fa6ef475d5] Updated javadocs
Build step 'Git Publisher' marked build as failure
Finished: FAILURE

I tried following from 143 shell prompt and got the same issue
git add docs/_docs/javadoc
git commit -a -m "Updated javadocs"
git push
