### ISSUE TITLE
Runtime determination of service/nonservice process nature

### ISSUE THREAD

**Issue by donaldoakes** [CenturyLinkCloud/mdw#220]
Up till now MDW insists on the service/nonservice aspect of a process being fixed at design time.  This affects retriability, synchronicity and other runtime behavior.  Recently apps are demanding more flexibility.  For example, in some contexts a master process is expected to be invoked synchronously (online ordering), whereas in other contexts the same master flow will return only an HTTP 202 acknowledgement after spawning many subflows asynchronously.

Two main aspects of this proposed enhancement:
1. **Retriability** - Adapter failure inside a service process should ignore Retry configuration.  Since the whole point of a service process is that it finishes on a single thread, it makes no sense to support retry intervals.
2. **Synchronicity** -  When a service process synchronously invokes another service process that fails, it rightly propagates the exception without waiting for the subflow to complete.  Again, this is the very nature of a service process.  This means that the calling process does not respond once the failed subflow is corrected/completed.

If the determination of service/nonservice could be postponed until runtime, then the same process design could accommodate both realtime and async behavior.  The subprocess adapter in point 1 would retry only in nonservice mode.  As for point 2, the calling process would wait for errored subflow completion only in nonservice mode as well.

This seems a sensible approach.  However, it is a new precedent to have the runtime engine paying attention to process state for this purpose.  Rather than attempting to make this into a general capability, I propose that we introduce a convention whereby a special variable (say *$service*) would be honored by the engine to override the design attribute if present.  There are bound to be repercussions that we'll need to discuss.  Comments are welcome.

**Comment by donaldoakes** [comment]
Maybe *$service* should be a parameter in the subprocess plan.

**Comment by jbrojdeCTL** [comment]
Any adapter that extends from PoolableAdapterBase will only retry is the process is NOT running as a service.  This way, a service process (specified at design time) can be designed to have adapter activities retry, but will only do so if not running as a service process.   Service processes can be invoked to run as regular processes when invoked Async from either a InvokeSubProcessActivity or InvokeHeterogenousProcessActivity.
