### ISSUE TITLE
Handle incoming JWT token when using Layer 7 Gateway authentication 

### ISSUE THREAD

**Issue by jbrojdeCTL** [CenturyLinkCloud/mdw#221]
When apps deploy to PCF, they can set up authentication for Services via layer 7 gateway, which will replace the contents of the Basic Auth header ("Authorization") with a JWT token.  MDW needs to ignore that token instead of attempting to authenticate again with said token, since that won't work.

**Comment by donaldoakes** [comment]
Or we could consider the option to actually validate the token: https://jwt.io.  If we don't do that here, we can make it an enhancement covered by a separate issue.

**Comment by jbrojdeCTL** [comment]
If Authorization header is present, but value doesn't start with "Basic", MDW will ignore it.   Applications will make use of the startup parameter "-Dmdw.service.api.open=true" in conjunctions with the mdw_access property  "serviceUser: <validauthorizeduser>" in order to allow access to hosted Services.   URL provided to consumers of such services will be that of the layer 7 gateway, not of the PCF deployment.

**Comment by jbrojdeCTL** [comment]
Issue #222 was created to use/validate JWT token
