### ISSUE TITLE
JWT Authentication for services

### ISSUE THREAD

**Issue by donaldoakes** [CenturyLinkCloud/mdw#222]
Requirements:
 - Hub authentication for UI access.
 - Service authentication per config.
 - Designer auth for remote/runtime access.
 - Mobile sign in (https://github.com/CenturyLinkCloud/mdw-mobile/issues/7)
 - Single, global set of credentials for each MDW user.
 - Workgroups and Roles are granted per-env as usual.

Proposed Impl:
 1. Provider implementation in internal cloud asset package:
   - Based on https://github.com/auth0/java-jwt
   - Exposed as a REST API for remote access.
   - We'll use this for AppFog, and scrap our dependency on oltu.
   - Passwords are one-way hashed and stored in ATTRIBUTES.
   - Submitted credentials are validated against hashed passwords.
 2. New authMethod `mdw` in access.yaml.
  - Consume the REST API from 1 to authenticate.
  - Client apps must request an MDW token, which will be used for accessing the service.
  - Add authMethod to AppSummary response JSON.
 3. Deployed centrally to AppFog Prod.
  - Self-serve user account creation (JSX UI in internal package).
  - Users can create an account simply by verifying their email address.
  - All access must be through HTTPS.
 4. Logging in (**service access through HTTPS**):
  - Designer: based on AppSummary authMethod, use `mdw` auth (https://github.com/CenturyLinkCloud/mdw-designer/issues/48).
  - Hub: new AngularJS login page and updates in AuthenticatedUser service.
  - Hub: For client apps where authMethod=mdw, adding a user should be through a typeahead input (similar to searching for users).  The available values for this user typeahead will come from mdw-central.
  - New [Authenticator](https://centurylinkcloud.github.io/mdw/docs/javadoc/com/centurylink/mdw/auth/Authenticator.html) impl: JwtAuthenticator.
  - Mobile: as described in https://github.com/CenturyLinkCloud/mdw-mobile/issues/7.

**Comment by magrawa** [comment]
![app table](https://user-images.githubusercontent.com/9357745/36167601-b083a1a4-10b3-11e8-92de-356f467b5cf0.JPG)
![design](https://user-images.githubusercontent.com/9357745/36167603-b0a525fe-10b3-11e8-90ca-538e46eb08ba.JPG)

**Comment by magrawa** [comment]
@jbrojdeCTL

**Comment by magrawa** [comment]
Should we allow users to be searched by user id or name or both?
