### ISSUE TITLE
Kafka Listener

### ISSUE THREAD

**Issue by donaldoakes** [CenturyLinkCloud/mdw#247]
Implement a Kafka pub/sub listener that can leverage the existing EventHandler mechanism.  This should exist in its own asset package so that it can be an optional component: **com.centurylink.mdw.kafka**.

**Comment by donaldoakes** [comment]
Depending on requirements, we may need to consider a mechanism for topic-based routing vs content-based routing.

**Comment by jbrojdeCTL** [comment]
The listening part will have to be based on topic, but the MDW routing would be based on content

**Comment by donaldoakes** [comment]
We may need flexibility around this.  For now you can implement to subscribe on a standard topic and route based on content.  However, I have a feeling that CRMP and other apps will want to route based on topic.  In fact, maybe we need to consider how to enhance the EventHandler mechanism so that any protocol can use path/topic based routing like we already do for REST services.

**Comment by jbrojdeCTL** [comment]
I was thinking that as part of the listener registration, one could specify a default handler (topic based), which would apply whenever there is no content-based handler defined

**Comment by donaldoakes** [comment]
Sure, you can do that.  Longer-term I think we should add a new option in evth files:
```
{
  "handlerClass": "START_PROCESS?ProcessName=com.centurylink.mdw.tests.services/FindEmployee",
  "path": "GetEmployee",
  "routing": "path|content"
}
```
If routing is missing or "content", we proceed as usual.  If routing is "path", then depending on protocol the `path` field would be interpreted as a topic, url path, etc.

As apps move away from content-based routing, they'll want something like this or else they'll be tempted to implement their own listener logic.

**Comment by jbrojdeCTL** [comment]
I think a bigger problem with our event handlers is that they only apply when message is XML.  For CRMP, the content will apparently be JSON, so no event handler would even work there.   An easy way to handle this would be to have the app create a ServiceRequestHandler java class in an app pkg that will handle their Kafka requests (and they could sort it out based on topic or content based on their needs), and we would find their custom handler by them specifying the pkg name that contains their handler as one of the Kafka listener properties.

**Comment by donaldoakes** [comment]
Path-based routing is superseded by issue #250.

**Comment by jbrojdeCTL** [comment]
This requires env to have the com.centurylink.mdw/kafka package, and to configure it via properties as explained in readme.md in kafka pkg
