### ISSUE TITLE
Better handling of asset versions to prevent inflight issues caused by failure to increment

### ISSUE THREAD

**Issue by donaldoakes** [CenturyLinkCloud/mdw#256]
It's too easy for app teams to ignore best practice and fail to increment asset (especially process) versions when making structural changes.  This causes major headaches with inflight when incompatible same-versioned assets are imported.  We need to take a hard look at how we can prevent this from happening.

### Scenario 1 (process change):
Process myproc v0.1 is running in production.  For an enhancement, a new input variable "myjson" is added to the process, and a script activity downstream of an event wait is updated to retrieve a value: `myjson.getString('myprop')`.  The developer fails to increment myproc, and imports the update myproc v0.1 into prod.  After deployment an inflight instance of myproc that was stopped at the event wait is now cleared to resume (the event is received).  Since the new definition is indistinguishable from the old, the inflight instance resumes using the new def.  It hits the script activity and a NullPointerException is thrown because the required "myjson" variable was never populated.

### Scenario 2 (asset-driven activity):
(Moved to issue #260)

**Comment by donaldoakes** [comment]
I've given some thought to Scenario 1, and I think our approach should be to prevent this on asset import as we used to do with the old Designer import mechanism.  Thanks to the ASSET_REF table, we have the Git commit hash and process id associated with myproc v0.1.  We should check existing ASSET_REFS to see if there is a same-or-earlier version extant, and in that case we should abort the import with an appropriate error message.

**Comment by donaldoakes** [comment]
Scenario 2 asset-driven activities:
| Activity | Asset Type |
| -------- | ---------- |
| Autoform Manual Task  | Task Template  |
| Camel Route Adapter  | Route Definition  |
| Crossmap Activity | Mapping Script |
| Custom Manual Task | Task Template |
| Drools Activity | Knowledge Base |
| Drools Decision Table | Excel Spreadsheet |
| Notification | E-Mail Template |
| Velocity Activity | Velocity Template |

**Comment by jbrojdeCTL** [comment]
This issue is fixed for MDWHub imports or any method that uses VcsArchiver.java to perform the import of assets.   For MDW CLI, see issue #267
