### ISSUE TITLE
Newly-added user sometimes not reflected in user list

### ISSUE THREAD

**Issue by PabitraKumar-Behera** [CenturyLinkCloud/mdw#26]
(Renamed this issue to more specifically describe the problem).
When a user is added or has their roles modified, this needs to trigger a distributed UserGroupCache refresh so that all instances reflect this change in a clustered environment.

**Comment by vimala-nagarja-CTL** [comment]
This issue is not reproducible.

**Comment by donaldoakes** [comment]
Reopening this issue to keep it as a low priority.  This probably is only reproducible in a multi-server environment, so we need to try and reproduce it there.  Probably we need to propagate the introduction of the user into the memory cache in other instances.
