### ISSUE TITLE
Have MDW change the contextClassLoader to be a CloudClassLoader

### ISSUE THREAD

**Issue by jbrojdeCTL** [CenturyLinkCloud/mdw#262]
Currently, if application code is making use of third-party libraries which load additional classes, the classLoader that ends up getting used is the default Tomcat WebappClassLoader, which cannot find classes located in the application's assets.   Change BaseActivity.java to change the current thread's context class loader to be the cloudclassloader from the package of the activity, and then restore it once activity finishes executing, and also do this in ListenerHelper.java so that event handlers and services can also benefit of being able to find classes located under assets.

**Comment by jhliptak** [comment]
This needs to be really well documented for users so they limit their assets to thread safe libraries.  Any thread pool use in those libraries for things like lambda's, streams, etc. that use fork/join or any other multiple thread algorithm will fail, some with very difficult to repeat race conditions.

**Comment by jbrojdeCTL** [comment]
After some initial testing resulted in many errors, we decided to not implement this as initially envisioned.  Instead, we are providing an API in ApplicationContext class that can be called whenever needed to change the current thread's context class loader to a cloud class loader, and to reset it back to the original class loader.  MDW will also attempt to catch when an application changes the context class loader but fails to reset it once the change is not needed, and reset it for the user.
