### ISSUE TITLE
mdw-admin caching issue

### ISSUE THREAD

**Issue by PabitraKumar-Behera** [CenturyLinkCloud/MDW#27]
If a user is added in the mdw-admin app, it doesn't appear in the list of users until either the cache is cleared in the browser or, in the case of Appfog ( mdwdemo.useast.appfog.ctl.io/mdw ), the app has to be restarted. This also sometimes occurs locally when adding a role to a user and you are unable to see the role in the user's list of roles. This can result in multiple identical roles being able to be added to a user and another "duplicate key" error being shown in "Developer Tools" since the user now has multiple identical roles. Possible solutions to look at for client side ...Add cache-control headers on the page... add an http interceptor...add own template cache

**Comment by donaldoakes** [comment]
Moved to 5.5.
