### ISSUE TITLE
MDWHub - show server name of activity instance/process instance

### ISSUE THREAD

**Issue by ibisset-centurylink** [CenturyLinkCloud/mdw#278]
For debugging and general troubleshooting, it would help if, when looking at an activity instance or process instance in MDWHub, the information on which server the instance ran on, would be displayed.

**Comment by donaldoakes** [comment]
Should we consider integrating with Splunk for this?  I think Splunk should be able to reconcile log entries across instances.

**Comment by ibisset-centurylink** [comment]
TBH, not sure what Splunk does. I did see an ENGINE_ID column in ACTIVITY_INSTANCE that isn't used. Maybe this column was initially targetted for this? Although I guess it's not that easy, especially for activities that can potentially start/restart/resume on different servers.
