### ISSUE TITLE
Arbitrary attributes for Users and Workgroups

### ISSUE THREAD

**Issue by donaldoakes** [CenturyLinkCloud/mdw#289]
On MDWHub's Admin tab, when editing a user the page will display all unique existing ATTRIBUTE names from the db for possible data entry (besides always including email and phone).  You can try this out by inserting a value for your user id into ATTRIBUTE.  Then when you edit any user other than yourself the attribute will show up as an enterable text field.

Beyond this, we also need an Advanced button on the user edit form to enable entry of any arbitrary ATTRIBUTE name/value.

Also, we need to extend this capability to Workgroups.  We will use this to enter and track the Slack channels associated with each Workgroup.

**Comment by magrawa** [comment]
Should we also add this functionality for Solution as listed in in this [issue ](https://github.com/CenturyLinkCloud/mdw/issues/24)

**Comment by magrawa** [comment]
Add this functionality to Solution but use value table.
Create "Slack Channel Name" as a hard-coded attribute.

**Comment by magrawa** [comment]
Do we add "Slack Channel" only to Workgroup tab and not to user tab?
