### ISSUE TITLE
Publish mdw 6.0.x war/jars to Maven Central

### ISSUE THREAD

**Issue by donaldoakes** [CenturyLinkCloud/mdw#3]
We no longer need to publish to Nexus.  We'll publish to these two repositories:
 - http://repo1.maven.org/maven
 - http://lxdenvmtc143.dev.qintra.com:7021/maven/repository

Needed to publish to Maven Central:
 - Javadocs jars (for each project)
 - PGP signing
 - Comprehensive POM data

Full requirements:
http://central.sonatype.org/pages/requirements.html

Other Resources to enable publishing:
https://maven.apache.org/guides/mini/guide-central-repository-upload.html
https://docs.gradle.org/current/userguide/maven_plugin.html

**Comment by donaldoakes** [comment]
At this time we depend exclusively on Maven Central artifacts.  The next step is to actually publish there.

**Comment by magrawa** [comment]
SNAPSHOT build was tested 
https://oss.sonatype.org/content/repositories/snapshots/com/centurylink/mdw/mdw/6.0.03-SNAPSHOT/
6.0.2 build was tested but never released. https://oss.sonatype.org/#welcome
We need to test it out when we do a formal build. Make sure -DPUBLISHING_TO_MAVEN_CENTRAL parameter is passed in Jenkins build configuration. Task name is publishToMavenCentral. We have to setup gradle.properties to use the right secrete key file.

**Comment by magrawa** [comment]
Do we need to publish these to maven central?
    <dependency>
      <groupId>com.centurylink.mdw</groupId>
      <artifactId>mdw-schemas</artifactId>
      <version>5.5.38-SNAPSHOT</version>
    </dependency>

**Comment by magrawa** [comment]
We do not need it because developers can use eclipse plug-in. Designer build requires this and we plan to offer that as premium feature 
/cc @donaldoakes

**Comment by magrawa** [comment]
auto signing did not work from Jenkins parameter
-DPUBLISHING_TO_MAVEN_CENTRAL=true -Psigning.keyId=xxxxx -Psigning.password=mdwbpmcore1 -DossrhUsername=xxxxx -DossrhPassword=xxxxxxxxxxxxx -Psigning.secretKeyRingFile=/prod/ecom2/local/apps/jenkins/workspace/MDW55\ -\ Build/mdw-framework/deploy/certs/secring.gpg

Had to put the properties in gradle.properties with remaining properties like this in Jenkins
-DPUBLISHING_TO_MAVEN_CENTRAL=true -DossrhUsername=xxxxxxxxxx -DossrhPassword=xx
 
Also, in next build check the createTag task to make sure tags are created after the publish

**Comment by magrawa** [comment]
added a jenkins build step to append these properties from sign.txt in the same dir as gradle.properties
