### ISSUE TITLE
Fix Sign Out page

### ISSUE THREAD

**Issue by magrawa** [CenturyLinkCloud/mdw#307]
Go to https://mdwjws-dev1.dev.intranet:40063/mdw

Click on Sign Out

https://mdwjws-dev1.dev.intranet:40063/mdw/logout

it should go to https://mdwjws-dev1.dev.intranet:40063/mdw/login

**Comment by donaldoakes** [comment]
ClearTrust will not terminate the session unless the target URL matches `cleartrust.agent.logout_form_location` from webagent.conf.  We **must** terminate the session when a user logs out.  Therefore my suggestion is to have the login form always post back to the login URL through its `action` attribute (regardless whether it is displayed by /logout or /login).
