### ISSUE TITLE
Spreadsheet-driven parameterized values in test cases

### ISSUE THREAD

**Issue by PabitraKumar-Behera** [CenturyLinkCloud/mdw#32]
Similar to the existing mechanism for Load Tests, but using XLSX files (though Apache POI) instead of only CSV files.
Also, generalize this so that it works for any test case and not just load tests.

**Comment by ab59451** [comment]
migrated this issue  to the mdw-designer repo. 
closed the issue,removed the milestone, removed the designer label and marked as duplicate in this repo.
