### ISSUE TITLE
Designer should handle bad or missing com.centurylink.mdw.plugin.xml

### ISSUE THREAD

**Issue by PabitraKumar-Behera** [CenturyLinkCloud/mdw#33]
Currently malformed or missing plugin.xml can cause extended pauses, mysterious errors in Eclipse (especially when right-clicking on a project in Package Explorer). Error message should indicate offending file. Show something friendly to help the user understand what the problem is.

**Comment by ab59451** [comment]
migrated this issue  to the mdw-designer repo. 
closed the issue,removed the milestone, removed the designer label and marked as duplicate in this repo.
