### ISSUE TITLE
Remove Archive directory creation from Import

### ISSUE THREAD

**Issue by donaldoakes** [CenturyLinkCloud/mdw#338]
Now that the ASSET_REF concept has been proven stable, we should remove the old directory-based archiving from VcsArchiver.

This causes complications with dynamic Java startup services.

For example:
```java
@RegisteredService(StartupService.class)
public class AutoTestWebSocketClient
```
was removed from package com.centurylink.mdw.testing.  However because it still lives in the Archive it continues to get compiled (and shows errors because it's dependencies no longer exists).

This also causes potential confusion as to where to look for old asset versions (Git commit vs directory).

Also, directory archiving consumes extra (wasted) time during import.  For the time being, we will retain compatibility for **loading** from the Archive if it exists.

**Comment by vimala-nagarja-CTL** [comment]
The spring asset from deleted package still gets loaded on tomcat server start up as it is still present in Archive.
