### ISSUE TITLE
Task Event Wait registration service

### ISSUE THREAD

**Issue by PabitraKumar-Behera** [CenturyLinkCloud/mdw#34]
Restore/implement the following methods in WorkflowServicesImpl and expose through REST. Also make sure non-recurring event waits work with Custom and Autoform manual tasks.
//    void registerTaskWaitEvent(Long taskInstanceId, String eventName)
//            throws ServiceException;
//
//    void registerTaskWaitEvent(Long taskInstanceId, String eventName, String completionCode)
//                    throws ServiceException;

**Comment by jbrojdeCTL** [comment]
The /Tasks service allows for event registration, including a Completion Code when event arrives.   Only non-recurring type events are allowed (i.e. multiple waiters can exist for the same event), and the Task will begin listening for the event to arrive after it has registered.  Pre-arrived events will not trigger notification when registering via this REST service.
