### ISSUE TITLE
Associate related event wait/notify activities in Designer

### ISSUE THREAD

**Issue by PabitraKumar-Behera** [CenturyLinkCloud/mdw#35]
Make it convenient to find related Event Wait/Notify activities in Designer. These will have to be manually linked by the user, but after that double-clicking on the Wait activity should automatically open the associated process and highlight the associated Notify activity and vice-versa.

**Comment by ab59451** [comment]
migrated this issue to the mdw-designer repo.
closed the issue,removed the milestone, removed the designer label , removed the project and marked as duplicate in this repo.
