### ISSUE TITLE
Retire mdw-buildpack

### ISSUE THREAD

**Issue by donaldoakes** [CenturyLinkCloud/mdw#353]
Our Cloud Foundry support is now through the MDW Spring Boot executable jar:
http://centurylinkcloud.github.io/mdw/docs/getting-started/spring-boot/

With build 13 we'll retire the mdw-buildpack due to security vulnerabilities.

 - Move the mdw-buildpack codebase to internal GitLab for legacy support.
 - Remove, rename, or empty out the mdw-buildpack GitHub project (maybe just leave README.md).
 - Remove the CI step that automatically commits to mdw-buildpack.

We'll need to mention the mdw-boot CF deployment changes to manifest.yml in our Release Notes.

**Comment by magrawa** [comment]
moved content to https://ne1itcprhas62.ne1.savvis.net/MDW_DEV/mdw-buildpack

**Comment by magrawa** [comment]
Removed from travis build but left GitHub repo in place until TOMWF upgrades to 6.0.13 build.
