### ISSUE TITLE
Substititution in file when sending a notice

### ISSUE THREAD

**Issue by PabitraKumar-Behera** [CenturyLinkCloud/mdw#36]
When sending tokens in notify event using file command. Substitutions are not happening. Workaround it to copy the content in test script itself.  Or to use the "post http" syntax for sending the event.

**Comment by donaldoakes** [comment]
Use http option instead.

**Comment by ab59451** [comment]
migrated this issue to the mdw-designer repo.
closed the issue,removed the milestone, removed the designer label , removed the project and marked as duplicate in this repo.
