### ISSUE TITLE
New Manual Task Activity: Fallout Task

### ISSUE THREAD

**Issue by PabitraKumar-Behera** [CenturyLinkCloud/MDW#38]
This will be the default for embedded exception handler subprocesses, and it will have a pagelet for it's task template that has reasonable defaults for variable expressions to display. This builds on the work Jack has done for Issue #24, and requires that AutoForm Tasks are able to evaluation expressions in MDWHub (Issue #36).

**Comment by donaldoakes** [comment]
Moved to 5.5.
