### ISSUE TITLE
Self awareness for MDW instances for things like asset imports and cache refreshes

### ISSUE THREAD

**Issue by jbrojdeCTL** [CenturyLinkCloud/mdw#389]
Currently, whenever there's an asset import or a cache refresh, MDW performs a propagation of the action by sending a message to each of the other instances as configured in mdw.server.list property.   This is not a viable approach in the case of PaaS since instances can be scaled up and down on demand, and we have no way of knowing how many, or how to reach each one directly (i.e. PCF, Docker, etc).    

Each MDW instance will need to be self aware of the need to import assets or refresh cache based on saved state information in the database (i.e. last commit, timestamp of last cache refresh, etc), by checking periodically if it needs to perform any of these actions.

**Comment by donaldoakes** [comment]
With this can we get rid of the `IsIntraRequest` concept in AccessFilter?

**Comment by donaldoakes** [comment]
Crawler has been committed.  Still needs some testing in different cases, like jsx pages.
