### ISSUE TITLE
When downloading remote package zips, sometimes a painful workspace refresh is triggered

### ISSUE THREAD

**Issue by PabitraKumar-Behera** [CenturyLinkCloud/mdw#39]
When this happens, for each asset file extracted a workspace refresh can be triggered which makes it take forever to unzip the file. A workaround seems to be to mark the project .temp folder as derived (right-click folder in Package Explorer > Properties > Resource > Derived). It would be great to perform this programmatically when first discovering the remote environment, or to avoid this pain in some other way.
The remote project where I experienced this behavior is WFMT VCS Dev 2. It seems occur after a few Process Explorer refreshes if that's any clue.

**Comment by PabitraKumar-Behera** [comment]
We should be able to programmatically mark the .temp folder as derived.

**Comment by ab59451** [comment]
migrated this issue to the mdw-designer repo.
closed the issue,removed the milestone, removed the designer label , removed the project and marked as duplicate in this repo.
