### ISSUE TITLE
Zero-db Designer access for mdw6

### ISSUE THREAD

**Issue by donaldoakes** [CenturyLinkCloud/mdw#4]
We need to update DesignerDataAccess so that for mdw6 only userAccessServer is consulted to check groups/roles/etc, and not the userinfo member.  At the same time we can not require db credentials in com.centurylink.mdw.plugin.xml.  In other words, all access from Designer in mdw6 is through REST.  And the db fields in the Project Properties page should be suppressed.

Anyway, for VCS assets db connection is only a fallback for user permissions so that the server does not have to be running. But we should make a running server a prerequisite for any of these type operations anyway.

Also as part of this we should change the defaults in Designer so that the default db points to embedded db in the project creation wizards.

**Comment by naveena-bellamkonda** [comment]
Leave a comment
