### ISSUE TITLE
WorkflowServices should provide filtering process instances by variable value

### ISSUE THREAD

**Issue by PabitraKumar-Behera** [CenturyLinkCloud/mdw#40]
Similar to what's provided in the ProcessInstances service used by Designer.  Hopefully this can be accomplished with zero impact to queries where variables are not part of the criteria.

Also, support for more complex conditions like != and ||.

**Comment by magrawa** [comment]
MDW CLI testing allows exclusion on test cases

**Comment by donaldoakes** [comment]
Here are the parameters supported by the MDW API for querying process instances:
Here's an example of an API request by variable value (url-encoded):
```
http://localhost:8080/mdw/api/processes?master=true&processId=244005592&variables=%7BmyStringVar%3Dabcdef%2CmyIntVar%3D123456%7D
```
Without encoding, the variables query param looks like this:
```
variables={myStringVar=abcdef,myIntVar=123456}
```
(enclose string variable value in single quotes if it contains a comma)

**Comment by donaldoakes** [comment]
Complex conditions will be a future enhancement.
