### ISSUE TITLE
Make Services tab API section work on Fuse

### ISSUE THREAD

**Issue by PabitraKumar-Behera** [CenturyLinkCloud/MDW#42]
WFMT raised this issue that https://wfmt.foss.corp.intranet/mdw-admin/index.html#/services is not working
Don's Suggestion Hint: set a breakpoint in MdwScanner around line 50 and step into the Reflections constructor and also getTypesAnnotatedWith() to see if we can additional parameter(s) in the Constructor. The constructor takes a varargs param group and you can pass in any order, so you could try something like:
if (ApplicationContext.isOsgi()) reflections = new Reflections(Assets.class.getPackage().getName(), Assets.class.getClassLoader());
Maybe additional ClassLoaders are needed besides mdw-listeners as above. If so, you can pass multiple ClassLoaders as separate params or in a list.
Output from Manoj's code change to fix this issue: It looks like Reflection object (store) is empty. I tried with multiple class loaders too. new Reflections("com.centurylink.mdw.service.rest", Assets.class.getClassLoader()).getTypesAnnotatedWith(Api.class)
returns zero size map.
Same with following call new Reflections("com.centurylink.mdw.service.rest", Assets.class.getClassLoader(), BaseActivity.class.getClassLoader()).getTypesAnnotatedWith(Api.class)
I than wrote small code without using Reflection api and that seems to work, which is like this
        Class aClass = com.centurylink.mdw.service.rest.Assets.class;
        java.lang.annotation.Annotation[] annotations = aClass.getAnnotations();
        for(Annotation annotation : annotations){
            if(annotation instanceof io.swagger.annotations.Api){
                io.swagger.annotations.Api myAnnotation = (io.swagger.annotations.Api) annotation;
                System.out.println("name: " + myAnnotation.value());
                System.out.println("value: " + myAnnotation.annotationType());
            }
        }

    }
Output: name: Workflow assets value: interface io.swagger.annotations.Api
Pending: Debug the Reflection api code to see why Annotated classes are not being loaded.

**Comment by PabitraKumar-Behera** [comment]
The following commit in mdw6 can be retrofitted to MDW 5.5 to fix the Swagger parsing on Fuse: https://github.com/CenturyLinkCloud/MDW/commit/a0f1d9464c357fb620a3beddee933fd850288d84

**Comment by donaldoakes** [comment]
Moved to 5.5.
