### ISSUE TITLE
Default activity attributes not saved in MDWHub asset editor

### ISSUE THREAD

**Issue by donaldoakes** [CenturyLinkCloud/mdw#427]
Many activity attributes have default values specified in the activity's .impl asset.  For example SendGridNotify.impl has the following:
```xml
<TEXT NAME='from' LABEL='From' VW='200' DEFAULT='support@example.com'/>
```
In Designer these values are populated when the process design is saved.  However, in MDWHub unless attributes are changed for an activity, the default values are not saved.  In the example above, the activity would be saved with no value for the `from` attribute.

**Comment by vimala-nagarja-CTL** [comment]
Hi Don,
  I was not able to reproduce the  issue.
  I tried to edit the workflow in hub from Assets menu and clicked on edit button. I dragged many activities which have default values and saved them from hub. I didn't modify any attribute of the activity (Did not choose the option to commit to Git).
 I opened the same workflow in designer and checked for all default values. They were present.

**Comment by jbrojdeCTL** [comment]
Vimala,
Hub will show the default attributes even when not set.   To verify if the attributes are actually set in activity, you must look at attributes tab (which shows you all values of the activity) instead of each individual tab.

**Comment by vimala-nagarja-CTL** [comment]
Hi Jack,
   I checked this from designer. default values for attributes are getting set.  From hub in  attributes tab, their values are not getting displayed. There is display problem

**Comment by jbrojdeCTL** [comment]
There is no issue when the designing is done using Designer, only when using Hub to add the activity to the process.   Te replicate, either edit a process, or create a new one using Hub, add an activity such as the rest adapter, and save the process.  You can then look at the process definition JSON content, and look for the rest adapter activity.  You will notice that the attribute "HttpMethod": "GET" is missing, but if you do these same steps using designer to add the rest adapter, the attribute will be there.
