### ISSUE TITLE
Create Pie Chart reports in MDWHub

### ISSUE THREAD

**Issue by PabitraKumar-Behera** [CenturyLinkCloud/mdw#43]
Create Pie charts for a given duration (week, month) which includes
Running Process Instances
Completed Instances
Failed Instances
Here is one example: https://camunda.com/img/camunda/product/reporting.png
How to use chartjs for Pie chart is here: http://www.chartjs.org/docs/#doughnut-pie-chart-introduction

**Comment by donaldoakes** [comment]
I think these breakdowns will come out-of-the-box with our existing aggregation services.  In other words you shouldn't need to create or modify the services.  You'll just need to change the existing data to optionally display in a Pie chart format in ChartJS.

The best way to get data for good transaction coverage is to execute a random sample of tests in a centralized environment that you can point against.  We already have this in our 5.5 dev int env:
https://lxdenvmtc144.dev.qintra.com:50960/mdw-admin/#/dashboard/processes

Preparatory to this enhancement, we need to add the random test executions as a Jenkins nightly build in our 6.0 dev int env just like we have in our 5.5 dev int env.  In the 5.5 codebase this is in the randomTests gradle task in tests.gradle.
