### ISSUE TITLE
Archived process request mappings cause conflicts

### ISSUE THREAD

**Issue by donaldoakes** [CenturyLinkCloud/mdw#433]
Archived processes with the same path as the current proc cause conflicts (noted in the startup log for the server).  Instead we should ignore archived processes when mapping request paths/methods to workflows.

**Comment by vimala-nagarja-CTL** [comment]
Hi Don,
  I have many archived packages in my local workspace and tried various things but not able to reproduce this issue.  Can you please give one example?

**Comment by vimala-nagarja-CTL** [comment]
In LoaderPersisterVcs.java,
 public List<PackageDir> getPackageDirs() throws DataAccessException {
        return getPackageDirs(false); // setting this to false will not fetch archived package directories.
    }
Since it is a very small change, I directly committed to master branch.
