### ISSUE TITLE
Provide a Bus example in com.centurylink.mdw.demo.camel

### ISSUE THREAD

**Issue by PabitraKumar-Behera** [CenturyLinkCloud/MDW#45]
In the Camel Demo project we should provide an example of launching an MDW process from the ctlbus component:
    <route>
      <from uri="ctlbus://Q.RESD5.test?account=camel&credentials=testing"/>
      
      <filter>
        <xpath>/Order</xpath>
        <to uri="mdw:process?name=com.centurylink.mdw.demo.camel/CamelDemoProcess&amp;masterRequestId=${Order/orderNumber/node()}"/>
      </filter>
BusResponder hanging threads prevent FOSS MDW deployments that use Tibco from shutting down cleanly: http://cshare.ad.qintra.com/sites/MDW/Lists/MDW%20Support/Shut%20down%20application%20is%20not%20working
According to John Liptak:
Jack is correct bus responders to not shut down correctly, they wait 10 seconds for each subject they subscribe to.
The best alternative is to use the TIBCO bus camel component to subscribe to tibco, this allows each multi-threading and configuration.
That’s why we have the specific question in the ORR that we don’t allow bus responder use in FOSS.
camel-bus.zip
See the attached implementation.

**Comment by PabitraKumar-Behera** [comment]
Title changed from Switch to Tibco Camel Component from BusResponder to Provide a Bus example in com.centurylink.mdw.demo.camel

**Comment by donaldoakes** [comment]
Moved to 5.5.
