### ISSUE TITLE
MDW Open Source Documentation

### ISSUE THREAD

**Issue by PabitraKumar-Behera** [CenturyLinkCloud/mdw#47]
In preparation to go open source with MDW , we want to create documentation like other BPM open source projects like this one https://github.com/camunda/camunda-bpm-examples. Fisrt document would be Getting Started with MDW BPM it would be under https://github.com/CenturyLinkCloud/MDW/mdw-bpm-examples
In this Readme.md we need to transfer content from http://cshare.ad.qintra.com/sites/MDW/Developer%20Resources/Tutorials/MdwTomcatCookbook.html
While creating this document we should remove references to internal CenturyLink resources and terminology and figure out how to host those contents on GitHub. For example we need to start thinking about eclipse plug-in update site and code formatter location.

**Comment by PabitraKumar-Behera** [comment]
The camunda-bpm-examples URL actually points to a GitHub repository project. We can add the mdw-demo under MDW in GitHub, which will accomplish something similar to that. For documentation of mdw-demo, Morgan has already created some great content in mdw-demo/readme based on the cookbook as you suggest.
Aside from that, for pure documentation, I think we should consider GitHub Pages: https://pages.github.com/

**Comment by donaldoakes** [comment]
Ongoing activity.
