### ISSUE TITLE
Process version discrepancies

### ISSUE THREAD

**Issue by PabitraKumar-Behera** [CenturyLinkCloud/mdw#49]
Workflow process versions are stored in the .proc JSON definition and also in .mdw/versions. Discrepancies can cause major headaches. Removing version from the .proc file would be a major change because it would affect our ability to handle in-flight processes. However, we should at least perform some checks during import/export and when initializing.
One problem this causes is when launching a process from the Workflow tab of MDWHub. If the versions don't match, then the backend REST service may return a 404 response.

**Comment by donaldoakes** [comment]
In mdw6 we'll no longer save versions in .proc assets.  In MDW 5.5 we have the option to validate for mismatches from Designer.
