### ISSUE TITLE
Use all_tab_cols in db self-upgrade check for Oracle

### ISSUE THREAD

**Issue by donaldoakes** [CenturyLinkCloud/mdw#490]
Otherwise this requires that the app db user must **own** the relevant table instead of just having read access.

**Comment by jbrojdeCTL** [comment]
Change made.  However, having visibility to the table via the all_tab_cols view doesn't mean having privileges to perform a DDL command against that schema.  At least this way, it will stop trying to perform the upgrade when it doesn't need to, but will throw exception for not being able to perform the DB upgrade if in fact it does need to.  A DBA would then still be needed if dev team has no access to schema owner account.    As a general rule, the recommendation is to always specify mdw.database.username property be the actual schema owner of the MDW tables.
