### ISSUE TITLE
Rest Adapters should error/fail when they receive a non-2xx HTTP code

### ISSUE THREAD

**Issue by jbrojdeCTL** [CenturyLinkCloud/mdw#511]
Currently, Reast adapters will throw an exception if a code 500 is returned, but proceed normally when a code 400, 401, 403, 404, etc code is returned.

**Comment by varunairi** [comment]
Can you make it configurable through a designer setting rather than always throwing exception

**Comment by jbrojdeCTL** [comment]
The http code value to be used as threshold is configurable, but with a custom implementer pagelet that shows the field, same as the retry http code threshold, which is also not visible on the out of the box adapter implementors.
