### ISSUE TITLE
Import remote Git VCS project does not need deep clone

### ISSUE THREAD

**Issue by PabitraKumar-Behera** [CenturyLinkCloud/mdw#52]
For Git VCS remote projects, importing in Designer can take a very long time. Currently we needlessly clone the entire repo history. Explore whether there's an option in JGit to do something similar to the _--depth_ option in _git clone_.

**Comment by ab59451** [comment]
migrated this issue to the mdw-designer repo.
closed the issue,removed the milestone, removed the designer label , removed the project and marked as duplicate in this repo.
