### ISSUE TITLE
Automated Test modularity enhancements

### ISSUE THREAD

**Issue by PabitraKumar-Behera** [CenturyLinkCloud/mdw#53]
- Support parameterized input values.
- Ability to call one test from another, passing inputs.
- Code reuse via shared Groovy classes or similar.
- Read and set runtime MDW properties for execution (set should apply only for test exec).

These changes should work in both Designer and MDWHub.

**Comment by ab59451** [comment]
migrated this issue to the mdw-designer repo.
closed the issue,removed the milestone, removed the designer label and marked as duplicate in this repo.
