### ISSUE TITLE
Enhanced mdw.git.autopull

### ISSUE THREAD

**Issue by donaldoakes** [CenturyLinkCloud/mdw#535]
(The name above makes more sense than our current `mdw.git.auto.pull`).

End-user asset management in MDWHub is not as friendly as it could be because of the potential for Git conflicts when multiple users are editing assets through the web.  A good way to solve this would be to extend autopull so that it automatically keeps the instance up-to-date with Git by pulling periodically (maybe in the AssetImportMonitor thread).

**Comment by jbrojdeCTL** [comment]
mdw.git.auto.pull will no longer try to do a pull upon startup.  Instead, the AssetImportMonitor will automatically do a git pull whenever it detects there's a new commit on the remote repo that it can pull.
