### ISSUE TITLE
Error reports should be sent through a REST service instead of SMTP

### ISSUE THREAD

**Issue by PabitraKumar-Behera** [CenturyLinkCloud/mdw#55]
We need to create a REST service for error reporting. Designer should use this service instead of JavaMail for error reporting. We can make this service generic enough so that in the future it can be used by other clients (like MDWHub).

**Comment by ab59451** [comment]
migrated this issue to the mdw-designer repo.
closed the issue,removed the milestone, removed the designer label , removed the project and marked as duplicate in this repo.
