### ISSUE TITLE
Swagger and Browser issues

### ISSUE THREAD

**Issue by PabitraKumar-Behera** [CenturyLinkCloud/mdw#57]
Swagger seems to be failing in Internet Explorer, and in Chrome some characters are looking funkyswaggerissues.docx
Can be debugged by looking at the console.
This may need a new version of Swagger ui

**Comment by donaldoakes** [comment]
Also, in deployed envs (as opposed to local), Swagger editor shows funny characters like â‡„	where it should be displaying expand/contract glyphs.

**Comment by magrawa** [comment]
Fixes #57
