### ISSUE TITLE
More flexible adapter/activity stubbing

### ISSUE THREAD

**Issue by PabitraKumar-Behera** [CenturyLinkCloud/mdw#58]
Currently stubbing in Designer is all-or-nothing. You can only turn stubbing on/off globally. We need a more flexible approach that allows hard-wired responses only for certain adapters whether run with or without stubbing. This will work better when good data for actual calls cannot be relied on.
One option would be to invoke the self-hosted asset retrieval service (http://localhost:8080/mdw/asset/) to pull the hard-wired response that's available from the framework. In conjunction with issue #53, this would allow you to temporarily set the problem endpoint URL the asset URL. However this only works for GET. It might be worthwhile to implement a Stub REST service in the framework that can handle any request METHOD and return the desired response asset.

**Comment by ab59451** [comment]
migrated this issue to the mdw-designer repo.
closed the issue,removed the milestone, removed the designer label , removed the project and marked as duplicate in this repo.

**Comment by donaldoakes** [comment]
Reopening for SDWF.
