### ISSUE TITLE
MDW Hub Process UI view does not show correct color on waiting activity of a completed process

### ISSUE THREAD

**Issue by magrawa** [CenturyLinkCloud/mdw#74]
Run process named FalloutTaskTest

Open the instance and Proceed on Open Task (A4) from designer.
After the process is complete Task A4 is still in waiting status and and shown in Yellow but in MDW Hub view it shows in black.  I think task should be shown in Cancelled color in both places.

Example URL in MDW Hub
http://localhost:8080/mdw/#/workflow/processes/10216

**Comment by donaldoakes** [comment]
This was broken when implementing workflow edit features in hub-ui.  Fixed by passing the fill color instead of simply true to Workflow.rect().
