### ISSUE TITLE
Reflect role permissions real-time in context menus.

### ISSUE THREAD

**Issue by donaldoakes** [CenturyLinkCloud/mdw#76]
For Designer local projects using VCS Assets, permissions are determined when a project is expanded in Process Explorer view and cached in the model.  This means that the following scenario occurs, causing user confusion:
 - User expands their local project in Process Explorer while the server is shut down.
 - They edit a process, and then start their server.
 - When they right-click to try and run the process or a test case, the Run option does not appear in the menu.

An easy workaround is to refresh Process Explorer view.  However, it's not apparent to users that this is required.  It would be best to determine the permissions dynamically if the server is available.

**Comment by ab59451** [comment]
migrated this issue to the mdw-designer repo.
closed the issue,removed the milestone, removed the designer label , removed the project and marked as duplicate in this repo.
