### ISSUE TITLE
Need to update mdw designer templates when creating a new project

### ISSUE THREAD

**Issue by morgansheets** [CenturyLinkCloud/mdw#80]
When a new local project is created, some of the default values are populated with incorrect information:
1) On JDBC DataSource Settings, the Driver is populated with oracle.jdbc.OracleDriver. It should be org.mariadb.jdbc.Driver. As well, it would be nice if the password is populated.
2) The url for the asset import location needs to point to the correct location, once we have the new public location.
3) While creating a local project, if the user does not provide the Git Repository URL, the mdw.properties file should not be automatically populated for the mdw.git.local.path=..., mdw.git.remot.url=... and mdw.git.branch.master in mdw.properties file. This causes a confusion.

**Comment by naveena-bellamkonda** [comment]
Created a new issue for pom.xml correction and closing this issue as other things are fixed.
