### ISSUE TITLE
Stopping InProgress Test Cases when server shuts down

### ISSUE THREAD

**Issue by magrawa** [CenturyLinkCloud/mdw#83]
We need to update the status of InProgress to Stopped when server is shutdown while testCases are still running. Otherwise the Run button is disable due to following condition in tests.html ng-disabled="running().length > 0

mdw-function-test-results.json is the file which keeps the status of all test cases.
Possible statuses in TestCase.java
    public enum Status {
        Waiting,
        InProgress,
        Errored,
        Failed,
        Passed,
        Stopped // terminated by user
    }
TestingServicesImpl.processResultsFile(File, List<TestCase>) line: 202	

May be we can update the result file before starting a new TestCase run.

**Comment by magrawa** [comment]
This is a rare scenario where server is not cleanly shut down. Occurrence of this happening in prod is very less. But if we need to fix it then we do it during the server start.

**Comment by donaldoakes** [comment]
A good approach for this would be to add a registered StartupService implementation in asset package com.centurylink.mdw.testing that would check the test results JSON file for InProgress or Waiting cases and update all these to Stopped.
