### ISSUE TITLE
Cannot Discover assets for import in mdw-hub from repo on 143 server

### ISSUE THREAD

**Issue by jbrojdeCTL** [CenturyLinkCloud/mdw#91]
When trying to import assets via mdw-hub, if you enter the 143 discovery URL (http://lxdenvmtc143.dev.qintra.com:7021/Discovery/assets), it returns error message:

Discovery failed: Invalid response from: http://lxdenvmtc143.dev.qintra.com:7021/Discovery/assets

HTTP response from server was:
{"status": {
  "code": 500,
  "message": "Invalid response from: http://lxdenvmtc143.dev.qintra.com:7021/Discovery/assets"
}}

**Comment by donaldoakes** [comment]
Superseded by #215.
